[versions]
junit = "5.10.0"
mockito = "5.16.1"
assertj = "3.27.3"
lombok = "1.18.36"
bootstrapfx = "0.4.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
bootstrapfx-core = { module = "org.kordamp.bootstrapfx:bootstrapfx-core", version.ref = "bootstrapfx" }
